blank_issues_enabled: true
contact_links:
  - name: 💬 General question
    url: https://github.com/TritCoded/thoth/discussions
    about: Ask a question or start a discussion (if Discussions is enabled on this repo)
